module Register
    DEFAULT_GRAB_PORT_RETRY_TIMES = 10
    DEFAULT_BRIDGE_RETRY_TIMES = 2
    DEFAULT_BRIDGE_RETRY_DELAY = 2
    DEFAULT_BRIDGE_PROCESS_DELAY = DEFAULT_BRIDGE_RETRY_TIMES * DEFAULT_BRIDGE_RETRY_DELAY * 2
    DEFAULT_BRIDGE_CONN_TIMEOUT = 3
    DEFAULT_BRIDGE_INACTIVE_TIMEOUT = 2
    DEFAULT_APP_USER = 'app@baidu.com'
    DEFAULT_APP_PATH = 'N/A'
    SUPPORTED_BRIDGE_ACTION = ['register', 'unregister']
    INSTANCE_NOT_REGISTER = /info:app.*is null/
end
