module Register
    DEFAULT_GRAB_PORT_RETRY_TIMES = 10
    DEFAULT_BRIDGE_RETRY_TIMES = 2
    DEFAULT_BRIDGE_RETRY_DELAY = 2
    DEFAULT_BRIDGE_PROCESS_DELAY = DEFAULT_BRIDGE_RETRY_TIMES * DEFAULT_BRIDGE_RETRY_DELAY * 2
    DEFAULT_BRIDGE_CONN_TIMEOUT = 3
    DEFAULT_BRIDGE_INACTIVE_TIMEOUT = 2
    DEFAULT_APP_USER = 'app@baidu.com'
    DEFAULT_APP_PATH = 'N/A'
    DEFAULT_APP_CLUSTER = 'app_cluster'
    ACTION_REGISTER = 'register'.freeze
    ACTION_UNREGISTER = 'unregister'.freeze
    ACTION_CREATE = 'create'.freeze
    SUPPORTED_BRIDGE_ACTION = [ACTION_REGISTER, ACTION_UNREGISTER, ACTION_CREATE]
end
