---
# NATS message bus URI
mbus: nats://cloudfoundry_php:cloudfoundry_php@10.36.59.34:4343

logging:
  level: debug
  file: /home/work/register_manager/log/register.log

rpc:
  bridge: http://127.0.0.1:8310  #bridge address
  register_retry_delay: 2         #delay to register instance again.
  register_conn_timeout: 3        #connection timeout with bridge.
  register_inactive_timeout: 2    #connection inactive timeout with bridge.
