---
# NATS message bus URI
mbus: nats://127.0.0.1:4222

logging:
  level: debug
  file: /tmp/register/register.log

rpc:
  bridge: http://127.0.0.1:8088  #bridge address
  register_retry_delay: 2         #delay to register instance again.
  register_conn_timeout: 3        #connection timeout with bridge.
  register_inactive_timeout: 2    #connection inactive timeout with bridge.
